(cl:defpackage action_test-msg
  (:use )
  (:export
   "<ADDINTSACTION>"
   "ADDINTSACTION"
   "<ADDINTSACTIONFEEDBACK>"
   "ADDINTSACTIONFEEDBACK"
   "<ADDINTSACTIONGOAL>"
   "ADDINTSACTIONGOAL"
   "<ADDINTSACTIONRESULT>"
   "ADDINTSACTIONRESULT"
   "<ADDINTSFEEDBACK>"
   "ADDINTSFEEDBACK"
   "<ADDINTSGOAL>"
   "ADDINTSGOAL"
   "<ADDINTSRESULT>"
   "ADDINTSRESULT"
  ))

