// Generated by gencpp from file pub_sub_node/test.msg
// DO NOT EDIT!


#ifndef PUB_SUB_NODE_MESSAGE_TEST_H
#define PUB_SUB_NODE_MESSAGE_TEST_H

#include <ros/service_traits.h>


#include <pub_sub_node/testRequest.h>
#include <pub_sub_node/testResponse.h>


namespace pub_sub_node
{

struct test
{

typedef testRequest Request;
typedef testResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct test
} // namespace pub_sub_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pub_sub_node::test > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::pub_sub_node::test&) { return value(); }
};

template<>
struct DataType< ::pub_sub_node::test > {
  static const char* value()
  {
    return "pub_sub_node/test";
  }

  static const char* value(const ::pub_sub_node::test&) { return value(); }
};


// service_traits::MD5Sum< ::pub_sub_node::testRequest> should match
// service_traits::MD5Sum< ::pub_sub_node::test >
template<>
struct MD5Sum< ::pub_sub_node::testRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pub_sub_node::test >::value();
  }
  static const char* value(const ::pub_sub_node::testRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pub_sub_node::testRequest> should match
// service_traits::DataType< ::pub_sub_node::test >
template<>
struct DataType< ::pub_sub_node::testRequest>
{
  static const char* value()
  {
    return DataType< ::pub_sub_node::test >::value();
  }
  static const char* value(const ::pub_sub_node::testRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pub_sub_node::testResponse> should match
// service_traits::MD5Sum< ::pub_sub_node::test >
template<>
struct MD5Sum< ::pub_sub_node::testResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pub_sub_node::test >::value();
  }
  static const char* value(const ::pub_sub_node::testResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pub_sub_node::testResponse> should match
// service_traits::DataType< ::pub_sub_node::test >
template<>
struct DataType< ::pub_sub_node::testResponse>
{
  static const char* value()
  {
    return DataType< ::pub_sub_node::test >::value();
  }
  static const char* value(const ::pub_sub_node::testResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PUB_SUB_NODE_MESSAGE_TEST_H
